on: push
name: Run Go tests

jobs:
    test:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                go-version:
                    - 1.21
                    - 1.22
                    - 1.23
                    - 1.24
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: ${{ matrix.go-version }}
            - run: go test -v ./...
